const PDFDocument = require('pdfkit')

function generateReport(metrics, res) {
  const doc = new PDFDocument({ margin: 50 })

  res.setHeader('Content-Type', 'application/pdf')
  res.setHeader('Content-Disposition', 'attachment; filename=report.pdf')
  doc.pipe(res)

  doc.rect(0, 0, 612, 80).fill('#1D9E75')
  doc.fillColor('white')
    .fontSize(24)
    .font('Helvetica-Bold')
    .text('Report Automation Engine', 50, 25)
  doc.fillColor('white')
    .fontSize(11)
    .font('Helvetica')
    .text('Auto-generated report · ' + new Date().toDateString(), 50, 55)

  doc.fillColor('#1a1a1a')
    .fontSize(16)
    .font('Helvetica-Bold')
    .text('Summary Metrics', 50, 100)

  doc.moveTo(50, 120).lineTo(560, 120).strokeColor('#e5e5e5').stroke()

  const metrics_list = [
    { label: 'Total Revenue', value: 'N' + metrics.totalRevenue.toLocaleString() },
    { label: 'Total Orders', value: metrics.totalOrders.toString() },
    { label: 'Avg Order Value', value: 'N' + Math.round(metrics.avgOrderValue).toLocaleString() },
    { label: 'Top Region', value: metrics.topRegion },
  ]

  let x = 50
  metrics_list.forEach(function(m) {
    doc.rect(x, 130, 120, 60).fillColor('#f9f9f9').fill()
    doc.rect(x, 130, 120, 60).strokeColor('#e5e5e5').stroke()
    doc.fillColor('#999').fontSize(9).font('Helvetica').text(m.label, x + 10, 142)
    doc.fillColor('#1a1a1a').fontSize(14).font('Helvetica-Bold').text(m.value, x + 10, 158)
    x += 130
  })

  doc.fillColor('#1a1a1a')
    .fontSize(14)
    .font('Helvetica-Bold')
    .text('Revenue by Region', 50, 210)

  doc.moveTo(50, 228).lineTo(560, 228).strokeColor('#e5e5e5').stroke()

  let y = 238
  const maxVal = metrics.regionChartData[0] ? metrics.regionChartData[0].value : 1

  metrics.regionChartData.forEach(function(item) {
    const barWidth = Math.round((item.value / maxVal) * 300)
    doc.fillColor('#555').fontSize(10).font('Helvetica').text(item.name, 50, y)
    doc.rect(160, y, barWidth, 12).fillColor('#1D9E75').fill()
    doc.fillColor('#333').fontSize(10).text('N' + item.value.toLocaleString(), 470, y)
    y += 24
  })

  y += 10
  doc.fillColor('#1a1a1a').fontSize(14).font('Helvetica-Bold').text('Revenue by Product', 50, y)
  y += 18
  doc.moveTo(50, y).lineTo(560, y).strokeColor('#e5e5e5').stroke()
  y += 10

  const maxCat = metrics.categoryChartData[0] ? metrics.categoryChartData[0].value : 1
  metrics.categoryChartData.forEach(function(item) {
    const barWidth = Math.round((item.value / maxCat) * 300)
    doc.fillColor('#555').fontSize(10).font('Helvetica').text(item.name, 50, y)
    doc.rect(160, y, barWidth, 12).fillColor('#3266ad').fill()
    doc.fillColor('#333').fontSize(10).text('N' + item.value.toLocaleString(), 470, y)
    y += 24
  })

  y += 10
  doc.fillColor('#1a1a1a').fontSize(14).font('Helvetica-Bold').text('Orders by Status', 50, y)
  y += 18
  doc.moveTo(50, y).lineTo(560, y).strokeColor('#e5e5e5').stroke()
  y += 10

  metrics.statusChartData.forEach(function(item) {
    doc.fillColor('#555').fontSize(10).font('Helvetica').text(item.name, 50, y)
    doc.fillColor('#1a1a1a').fontSize(10).font('Helvetica-Bold').text(item.value + ' orders', 160, y)
    y += 24
  })

  doc.moveTo(50, 750).lineTo(560, 750).strokeColor('#e5e5e5').stroke()
  doc.fillColor('#999').fontSize(9).font('Helvetica')
    .text('Generated by Report Automation Engine · ' + new Date().toISOString(), 50, 758)

  doc.end()
}

module.exports = { generateReport }
